on:
  release:
    types: [created]

jobs:
  release:
    name: release for linux-arm and linux-i686
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            aarch64-unknown-linux-gnu,
            armv7-unknown-linux-gnueabihf,
            i686-unknown-linux-gnu,
            i686-unknown-linux-musl,
            arm-unknown-linux-gnueabi,
          ]

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Installing musl
        if: matrix.target == 'i686-unknown-linux-musl'
        run: sudo apt-get install musl-tools gcc-multilib
      - name: Installing needed Ubuntu armhf dependencies
        if: matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'armv7-unknown-linux-gnueabihf' || matrix.target == 'arm-unknown-linux-gnueabi'
        run: |
          sudo apt-get install -y -qq gcc-arm-linux-gnueabihf libc6-armhf-cross libc6-dev-armhf-cross
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: stable
          args: --locked --release --target ${{ matrix.target }}"
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf tononkira_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz tononkira
          shasum -a 512 tononkira_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz > tononkira_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha512
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/tononkira_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz
            target/${{ matrix.target }}/release/tononkira_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha512
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
